memmap: update for error handling friendliness
Caller can now check error code for determining pass / fail of the
memmap choice.

diff --git a/scripts/30mini-iso-menu b/scripts/30mini-iso-menu
--- a/scripts/30mini-iso-menu
+++ b/scripts/30mini-iso-menu
@@ -46,16 +46,21 @@ iso_chooser_step1() {
 
     echo "Loading $MEDIA_LABEL ..."
 
-    memmap_size="$(/usr/lib/mini-iso-tools/get_memmap_directive $MEDIA_SIZE)"
-    pmem_directive="memmap=$memmap_size"
-
     cmdline=iso-url=$MEDIA_URL
     cmdline="$cmdline iso-size=$MEDIA_SIZE"
     if [ "$VALIDATE_CHECKSUM" = "1" ]; then
         cmdline="$cmdline iso-256sum=$MEDIA_256SUM"
     fi
+
     cmdline="$cmdline iso-chooser-step2"
-    cmdline="$cmdline $pmem_directive"
+
+    memmap_size="$(/usr/lib/mini-iso-tools/get_memmap_directive $MEDIA_SIZE)"
+    if [ -z "$memmap_size" -o "$?" -ne "0" ] ; then
+        echo "failed to determine size reservation for memmap, debug shell"
+        /bin/sh
+    fi
+    cmdline="$cmdline memmap=$memmap_size"
+
     cmdline="$cmdline nokaslr"
     cmdline="$cmdline ---"
 
diff --git a/scripts/regions/get_memmap_directive b/scripts/regions/get_memmap_directive
--- a/scripts/regions/get_memmap_directive
+++ b/scripts/regions/get_memmap_directive
@@ -3,6 +3,10 @@
 # given an input size, return a memmap directive of memory to request to
 # protect
 
+err() {
+    echo "$@" 1>&2
+}
+
 set -e
 
 requested_size="$1"  # size in bytes of protected memory to reserve
@@ -11,13 +15,13 @@ input="$2"           # input file to read, or /proc/iomem
 if [ -z "$input" ] ; then
     input="/proc/iomem"
 elif [ ! -f "$input" ] ; then
-    echo "input file not found"
+    err "input file not found"
     exit 1
 fi
 
 directive=$(grep -E "100000000"'-.*System RAM' "$input" || true)
 if [ -z "$directive" ] ; then
-    echo "range at address 4GiB not found"
+    err "range at address 4GiB not found"
     exit 1
 fi
 
@@ -37,9 +41,9 @@ requested_MiB=$(((requested_KiB  + 1023) / 1024))
 requested_MiB=$(((requested_MiB  +    3) &   ~3))
 
 if [ "$requested_MiB" -gt "$range_MiB" ] ; then
-    echo "available memory insufficient"
-    echo "requested ${requested_MiB}MiB"
-    echo "available ${range_MiB}MiB"
+    err "available memory insufficient"
+    err "requested ${requested_MiB}MiB"
+    err "available ${range_MiB}MiB"
     exit 1
 fi
 
